import { Project } from "@/types";

export const projects: Project[] = [
  {
    title: "Pokédex",
    description: "Immersive Pokémon Universe",
    coverImage: "/portfolio-images/pokedex/main.png",
    images: [
      "/portfolio-images/pokedex/1.png",
      "/portfolio-images/pokedex/2.png",
      "/portfolio-images/pokedex/3.png",
    ],
    liveUrl: "https://pokedex-rimsha-gul.vercel.app/",
    intro:
      "A must-have for Pokémon enthusiasts, offering an engaging and dynamic platform to discover and learn about various Pokémon. Built with modern web technologies, it ensures a smooth and interactive user experience.",
    features: [
      "Real-time Pokémon data fetching using GraphQL API",
      "Advanced search functionality for quick Pokémon retrieval",
      "Dynamic routing for direct access to individual Pokémon details",
      "Interactive Pokémon GIFs that respond to user interactions",
      "Responsive design for accessibility across all devices",
    ],
    skills: [
      "React",
      "GraphQL",
      "Apollo Client",
      "CSS",
      "styled-components",
      "Vercel",
    ],
  },
  {
    title: "Unithrive",
    description: "Comprehensive Healthcare Booking Solution",
    coverImage: "/portfolio-images/unithrive/main.png",
    images: [
      "/portfolio-images/unithrive/1.png",
      "/portfolio-images/unithrive/2.png",
      "/portfolio-images/unithrive/3.png",
      "/portfolio-images/unithrive/4.png",
      "/portfolio-images/unithrive/5.png",
      "/portfolio-images/unithrive/6.png",
      "/portfolio-images/unithrive/7.png",
      "/portfolio-images/unithrive/8.png",
      "/portfolio-images/unithrive/9.png",
      "/portfolio-images/unithrive/10.png",
      "/portfolio-images/unithrive/11.png",
      "/portfolio-images/unithrive/12.png",
      "/portfolio-images/unithrive/13.png",
    ],
    liveUrl: "https://unithrive.co/",
    intro:
      "Unithrive is a comprehensive web-based healthcare booking solution designed to streamline clinic operations. It offers a suite of features to enhance efficiency, manage patient bookings, and ensure compliance with healthcare regulations.",
    features: [
      "Multi-language support for global reach",
      "Multi-currency support for international transactions",
      "Dynamic pricing calculation",
      "Integration with third-party services such as SendGrid",
      "Responsive design for accessibility across devices",
    ],
    skills: ["Next JS", "React", "Typescript", "Tailwind CSS", "Azure"],
  },
  {
    title: "Purrfect Adoptions",
    description: "Streamlined Pet Adoption Platform",
    coverImage: "/portfolio-images/purrfect-adoptions/main.png",
    images: [
      "/portfolio-images/purrfect-adoptions/1.png",
      "/portfolio-images/purrfect-adoptions/2.png",
      "/portfolio-images/purrfect-adoptions/3.png",
      "/portfolio-images/purrfect-adoptions/4.png",
      "/portfolio-images/purrfect-adoptions/5.png",
      "/portfolio-images/purrfect-adoptions/6.png",
      "/portfolio-images/purrfect-adoptions/7.png",
    ],
    liveUrl: "https://purrfect-adoptions.vercel.app/",
    intro:
      "A comprehensive platform designed to simplify the pet adoption process. Purrfect Adoptions connects potential pet owners with shelters, streamlining the adoption workflow and providing real-time updates on the status of applications.",
    features: [
      "Multi-tiered adoption application workflow",
      "Real-time status updates for active applications",
      "Dynamic search and filtering system for pets and applications",
      "Shelter reviews to help users make informed decisions",
      "Responsive design for seamless functionality across various devices",
      "Automated expiration of applications based on predefined criteria",
      "Efficient file handling and image upload with Google Drive integration",
      "Real-time notification system for user updates and alerts",
      "Robust email services for account verification, password resets, and adoption updates",
    ],
    skills: [
      "React",
      "NodeJS",
      "ExpressJS",
      "MongoDB",
      "Typescript",
      "Socket.IO",
      "Multer",
      "NodeMailer",
      "Cypress",
      "Jest",
      "Vercel",
      "Openshift",
    ],
  },
  {
    title: "Arcompsol",
    description: "Company Website",
    coverImage: "/portfolio-images/arcompsol/main.png",
    images: [
      "/portfolio-images/arcompsol/1.png",
      "/portfolio-images/arcompsol/2.png",
      "/portfolio-images/arcompsol/3.png",
      "/portfolio-images/arcompsol/4.png",
      "/portfolio-images/arcompsol/5.png",
    ],
    liveUrl: "https://www.arcompsol.com/",
    intro:
      "Arcompsol provides innovative solutions aimed at helping businesses achieve digital transformation. Their offerings include a wide range of services such as web development, mobile app development, UI/UX design, AI and ML integration, big data analytics, and DevOps consulting.",
    features: [
      "Custom software development tailored to business needs",
      "Responsive web and mobile app design",
      "Integration of AI and ML for data-driven insights",
      "Big data analytics for informed decision making",
      "DevOps consulting to streamline operations",
    ],
    skills: ["React", "NextJS", "Typescript", "Material-UI"],
  },
  {
    title: "Clinic Booking System",
    description: "Efficient Clinic Management System",
    coverImage: "/portfolio-images/clinic-booking-system/main.png",
    images: [
      "/portfolio-images/clinic-booking-system/1.png",
      "/portfolio-images/clinic-booking-system/2.png",
      "/portfolio-images/clinic-booking-system/3.png",
      "/portfolio-images/clinic-booking-system/4.png",
      "/portfolio-images/clinic-booking-system/5.png",
      "/portfolio-images/clinic-booking-system/6.png",
      "/portfolio-images/clinic-booking-system/7.png",
      "/portfolio-images/clinic-booking-system/8.png",
      "/portfolio-images/clinic-booking-system/9.png",
      "/portfolio-images/clinic-booking-system/10.png",
      "/portfolio-images/clinic-booking-system/11.png",
      "/portfolio-images/clinic-booking-system/12.png",
    ],
    liveUrl: "https://demo.unithrive.co/",
    intro:
      "The Clinic Booking System by Unithrive offers a robust solution for managing clinic operations with advanced features to streamline bookings, enhance patient experience, and improve administrative efficiency.",
    features: [
      "Efficient booking management workflow to streamline appointment scheduling",
      "Real-time availability updates for doctors and resources",
      "Comprehensive patient management system",
      "Inventory management to track medical supplies and equipment",
      "Real-time updates on appointment statuses and clinic operations",
      "Multi-clinic management capability for scalable operations",
      "Schedule management for physicians, including time-offs and availability",
      "Comprehensive reporting and analytics for clinic performance",
    ],
    skills: ["React", "Ant Design", "Typescript", "CSS", "Firebase"],
  },
];
